src/UserBundle/Entity/User.php
<?php

namespace UserBundle\Entity;

use Symfony\Component\Security\Core\User\UserInterface;

class User implements UserInterface
{
    public const GENDER_UNKNOWN = '0';
    public const GENDER_MALE = '1';
    public const GENDER_FEMALE = '2';
    public const GENDER_ATTACK_HELICOPTER = '3';

    public const DEFAULT_AVATAR_PATH = '/themes/default/assets/images/default_avatar.jpg';
    public const DEFAULT_COVER_PATH = '/themes/default/assets/images/default_cover.jpg';

    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $username;

    /**
     * @var string
     */
    private $plainPassword;

    /**
     * @var string
     */
    private $password;

    /**
     * @var string
     */
    private $location;

    /**
     * @var integer
     */
    private $gender;

    /**
     * @var \DateTime
     */
    private $birthday;

    /**
     * @var string
     */
    private $introduction;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $token;

    /**
     * @var \DateTime
     */
    private $dateAvatarChanged;

    /**
     * @var \DateTime
     */
    private $dateCoverChanged;

    /**
     * @var \DateTime
     */
    private $dateCreated;

    /**
     * @var \DateTime
     */
    private $dateUpdated;

    public function __construct()
    {
        $this->dateCreated = new \DateTime();
        $this->dateUpdated = new \DateTime();
        $this->dateAvatarChanged = new \DateTime();
        $this->dateCoverChanged = new \DateTime();
        $this->gender = self::GENDER_UNKNOWN;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function getRoles(): array
    {
        return array('ROLE_USER');
    }

    public function getCurrentAvatarPath(): string
    {
        if (file_exists($this->getRealCurrentAvatarPath())) {
            return '/images/avatars/' . $this->getId()
                . '_avatar.jpg?t=' . $this->getDateAvatarChanged()->format('U');
        } else {
            return self::DEFAULT_AVATAR_PATH;
        }
    }

    public function getRealCurrentAvatarPath(): string
    {
        return __DIR__ . '/../../../web/images/avatars/' . $this->getId() . '_avatar.jpg';
    }

    public function getNewAvatarPath(): string
    {
        return '/images/avatars/' . $this->getId() . '_avatar_new.jpg';
    }

    public function getRealNewAvatarPath(): string
    {
        return __DIR__ . '/../../../web/images/avatars/' . $this->getId() . '_avatar_new.jpg';
    }

    public function getCurrentCoverPath(): string
    {
        if (file_exists($this->getRealCurrentCoverPath())) {
            return '/images/covers/' . $this->getId() . '_cover.jpg?t='
                . $this->getDateCoverChanged()->format('U');
        } else {
            return self::DEFAULT_COVER_PATH;
        }
    }

    public function getRealCurrentCoverPath(): string
    {
        return __DIR__ . '/../../../web/images/covers/' . $this->getId() . '_cover.jpg';
    }

    public function getNewCoverPath(): string
    {
        return '/images/covers/' . $this->getId() . '_cover_new.jpg';
    }

    public function getRealNewCoverPath(): string
    {
        return __DIR__ . '/../../../web/images/covers/' . $this->getId() . '_cover_new.jpg';
    }

    public function getFormattedBirthday(): string
    {
        return $this->getBirthday()->format('d - m - y');
    }

    public function getSalt(): string
    {
        return "kgA4aHTr64428rGFDZg8963";
    }

    public function encodePassword(): string
    {
        $this->setPassword(md5("Z".$this->password. $this->getSalt()));
        return $this;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): User
    {
        $this->username = $username;
        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $plainPassword): User
    {
        $this->plainPassword = $plainPassword;
        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): User
    {
        $this->password = $password;
        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): User
    {
        $this->location = $location;
        return $this;
    }

    public function getGender(): int
    {
        return $this->gender;
    }

    public function setGender(int $gender): User
    {
        $this->gender = $gender;
        return $this;
    }

    public function getBirthday(): ?\DateTime
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTime $birthday): User
    {
        $this->birthday = $birthday;
        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(?string $introduction): User
    {
        $this->introduction = $introduction;
        return $this;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): User
    {
        $this->email = $email;
        return $this;
    }

    public function getToken(): ?string
    {
        return $this->token;
    }

    public function setToken(string $token): User
    {
        $this->token = $token;
        return $this;
    }

    public function getDateAvatarChanged(): \DateTime
    {
        return $this->dateAvatarChanged;
    }

    public function setDateAvatarChanged(\DateTime $dateAvatarChanged): User
    {
        $this->dateAvatarChanged = $dateAvatarChanged;
        return $this;
    }

    public function getDateCoverChanged(): \DateTime
    {
        return $this->dateCoverChanged;
    }

    public function setDateCoverChanged(\DateTime $dateCoverChanged): User
    {
        $this->dateCoverChanged = $dateCoverChanged;
        return $this;
    }

    public function getDateCreated(): \DateTime
    {
        return $this->dateCreated;
    }

    public function setDateCreated(\DateTime $dateCreated): User
    {
        $this->dateCreated = $dateCreated;
        return $this;
    }

    public function getDateUpdated(): \DateTime
    {
        return $this->dateUpdated;
    }

    public function setDateUpdated(\DateTime $dateUpdated): User
    {
        $this->dateUpdated = $dateUpdated;
        return $this;
    }
}

src/UserBundle/Controller/SettingsController.php
<?php

namespace UserBundle\Controller;

use AppBundle\Service\ImageManipulator;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Bundle\TwigBundle\TwigEngine;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use UserBundle\Service\CurrentUserProvider;

class SettingsController extends Controller
{
    private $entityManager;
    private $logger;
    private $twig;
    private $formFactory;
    private $currentUserProvider;
    private $imageManipulator;
    private $currentUser;
    private $router;
    private $validator;

    public function __construct(
        EntityManagerInterface $entityManager,
        LoggerInterface $logger,
        TwigEngine $twig,
        FormFactoryInterface $formFactory,
        CurrentUserProvider $currentUserProvider,
        ImageManipulator $imageManipulator,
        RouterInterface $router,
        ValidatorInterface $validator
    ) {
        $this->entityManager = $entityManager;
        $this->logger = $logger;
        $this->twig = $twig;
        $this->formFactory = $formFactory;
        $this->currentUserProvider = $currentUserProvider;
        $this->imageManipulator = $imageManipulator;
        $this->currentUser = $this->currentUserProvider->getCurrent();
        $this->router = $router;
        $this->validator = $validator;
    }

    public function front(Request $request)
    {
        $form = $this->formFactory->createBuilder(FormType::class, null, [
            'attr' => [
                'id' => 'form'
            ]
        ])
            /*->add('username', TextType::class, [
                'attr' => [
                    'disabled' => '',
                    'placeholder' => $this->currentUser->getUsername()
                ]
            ])
            ->add('email', EmailType::class, [
                'attr' => [
                    'disabled' => '',
                    'placeholder' => $this->currentUser->getEmail()
                ]
            ])*/
            ->add('gender', HiddenType::class, [
                'data' => $this->currentUser->getGender()
            ])
            ->add('cover', FileType::class, [
                'required' => false,
                'label' => 'Cover'
            ])
            ->add('cover_changed', HiddenType::class, [
                'data' => 0
            ])
            ->add('cover_crop_values', HiddenType::class, [
                'data' => 0
            ])
            /*->add('cover_change_button', ButtonType::class, [
                'label' => 'Change Cover'
            ])*/
            ->add('avatar', FileType::class, [
                'required' => false,
                'label' => 'Avatar'
            ])
            ->add('avatar_changed', HiddenType::class, [
                'data' => 0
            ])
            ->add('avatar_crop_values', HiddenType::class, [
                'data' => 0
            ])
            /*->add('avatar_change_button', ButtonType::class, [
                'label' => 'Change Avatar'
            ])*/
            ->add('location', TextType::class, [
                'required' => false,
                'attr' => [
                    'placeholder' => 'Your Location',
                    'autocomplete' => 'off',
                    'value' => $this->currentUser->getLocation()
                ]
            ])
            ->add('birthday', BirthdayType::class, [
                'data' => $this->currentUser->getBirthday()
            ])
            ->add('introduction', TextareaType::class, [
                'required' => false,
                'data' => $this->currentUser->getIntroduction()
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Save Changes'
            ])
            ->getForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if (!$form->isValid()) {
                return new Response('', 403);
            }

            $this->currentUser
                ->setIntroduction($form->get('introduction')->getData())
                ->setLocation($form->get('location')->getData())
                ->setBirthday($form->get('birthday')->getData())
                ->setGender($form->get('gender')->getData())
            ;

            if ($form->get('avatar_changed')->getData() == 1) {
                $this->logger->debug('Avatar change was requested');
                if (file_exists($this->currentUser->getRealNewAvatarPath())) {
                    $this->logger->debug('New avatar found.');
                    if (file_exists($this->currentUser->getRealCurrentAvatarPath())) {
                        $this->logger->debug('Current avatar found, deleting.');
                        unlink($this->currentUser->getRealCurrentAvatarPath());
                    }
                    $this->logger->debug('Moving new avatar to current avatar.');
                    if (rename(
                        $this->currentUser->getRealNewAvatarPath(),
                        $this->currentUser->getRealCurrentAvatarPath()
                    )) {
                        $this->currentUser->setDateAvatarChanged(new \DateTime());
                    }
                }
            }

            if ($form->get('cover_changed')->getData() == 1) {
                $this->logger->debug('Cover change was requested');
                if (file_exists($this->currentUser->getRealNewCoverPath())) {
                    $this->logger->debug('New cover found.');
                    if (file_exists($this->currentUser->getRealCurrentCoverPath())) {
                        $this->logger->debug('Current cover found, deleting.');
                        unlink($this->currentUser->getRealCurrentCoverPath());
                    }
                    $this->logger->debug('Moving new cover to current cover.');
                    if (rename(
                        $this->currentUser->getRealNewCoverPath(),
                        $this->currentUser->getRealCurrentCoverPath()
                    )) {
                        $this->currentUser->setDateCoverChanged(new \DateTime());
                    }
                }
            }

            $errors = $this->validator->validate($this->currentUser);
            if (count($errors) > 0) {
                $errorString = (string) $errors;
                $this->logger->debug('Form validation errors: ' . $errorString);
                return new Response('DATA: ' . $form->get('location')->getData(), 400);
            }
            $this->entityManager->persist($this->currentUser);
            $this->entityManager->flush();

            return new Response('', 200);
        }

        return $this->twig->renderResponse('UserBundle:Settings:settings.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function cover(Request $request)
    {
        if ($request->isMethod('GET')) {
            return $this->twig->renderResponse('UserBundle:Settings:cover.html.twig', [
            ]);
        } else {
            /** @var File $file */
            $file = $request->files->get('file');
            $extension = $file->guessExtension();

            $this->logger->info('Uploading cover...', ['file_real_path' => $file->getRealPath()]);

            if ($extension === "png") {
                $image = $this->imageManipulator->convertPngToJpg($file->getRealPath());
            } else {
                if (!$image = imagecreatefromjpeg($file->getRealPath())) {
                    throw new \Exception('Image is not of valid format.');
                }
            }

            $width = imagesx($image);
            $height = imagesy($image);
            $cropArea = $request->request->get('cropValues');
            $cropArea = explode(",", $cropArea);

            $widthRatio = $width/$request->request->get('imgWidth');
            $heightRatio = $height/$request->request->get('imgHeight');

            $x1 = floor($cropArea[0] * $widthRatio);
            $y1 = floor($cropArea[1] * $heightRatio);
            $x2 = floor($cropArea[2] * $widthRatio);
            $y2 = floor($cropArea[3] * $heightRatio);
            $nWidth = $x2 - $x1;
            $nHeight = $y2 - $y1;

            $croppedImage = $this->imageManipulator->cropImageAdvanced($image, $nWidth, $nHeight, $x1, $y1, $x2, $y2);
            $resizedImage = $this->imageManipulator->resizeImage($croppedImage, $nWidth, $nHeight, 1170, 300);
            imagejpeg($resizedImage, $this->currentUser->getRealNewCoverPath(), 100);
            if (get_resource_type($croppedImage) == "gd") {
                imagedestroy($croppedImage);
            }
            if (get_resource_type($resizedImage) == "gd") {
                imagedestroy($resizedImage);
            }

            return new Response($this->currentUser->getNewCoverPath(), 200);
        }
    }

    /**
     * @param Request $request
     * @return Response
     * @throws \Exception
     */
    public function avatar(Request $request)
    {
        if ($request->isMethod('GET')) {
            return $this->twig->renderResponse('UserBundle:Settings:avatar.html.twig', [
            ]);
        } else {

src/UserBundle/Resources/views/Settings/avatar.html.twig
{% block cover %}
    <div class="ui segment" id="image_select_box">
        <img src="#" id="show_crop_avatar" align="middle">
        <br/>
        <button id="modal_crop_avatar_submit" type="button" class="ui inverted green button">Crop</button>
        <button id="modal_crop_avatar_cancel" type="button" class="ui inverted red button">Cancel</button>
    </div>
{% endblock %}

src/UserBundle/Resources/views/Settings/cover.html.twig
{% block cover %}
    <div class="ui segment" id="image_select_box">
        <img src="#" id="show_crop_cover" align="middle">
        <br/>
        <button id="modal_crop_cover_submit" type="button" class="ui inverted green button">Crop</button>
        <button id="modal_crop_cover_cancel" type="button" class="ui inverted red button">Cancel</button>
    </div>
{% endblock %}

src/UserBundle/Resources/views/Settings/settings.html.twig
{% extends "AppBundle::base.html.twig" %}

{% block additional_javascripts %}
    {% javascripts '@UserBundle/Resources/public/js/settings.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block body %}
    <div class="nav-body-gap"></div>
    <div class="ui form segment blue error four column grid padded" id="settings_box">
        {{ form_start(form, { 'attr': {'class': ''} }) }}
        {#<div class="disabled field six wide column">
            {{ form_label(form.username) }}
            {{ form_widget(form.username) }}
        </div>
        <div class="field">
            {{ form_label(form.email) }}
            {{ form_widget(form.email) }}
        </div>#}
        <div class="two fields">
            <div class="two wide field relative">
                {{ form_label(form.avatar) }}
                <div id="change_avatar_box">
                    <img src="{{ app.user.currentAvatarPath }}" id="avatar_preview" class="ui image small centered"/>
                    {{ form_widget(form.avatar, {'attr': {'class': 'file input'} }) }}
                </div>
                {#{{ form_widget(form.avatar_change_button, {'attr': {'class': 'ui fluid small blue button'} }) }}#}
                {{ form_widget(form.avatar_crop_values) }}
                {{ form_widget(form.avatar_changed) }}
            </div>
            <div class="six wide field relative">
                {{ form_label(form.cover) }}
                <div id="change_cover_box">
                    <img src="{{ app.user.currentCoverPath }}" id="cover_preview" class="ui fluid image"/>
                    {{ form_widget(form.cover, {'attr': {'class': 'file input'} }) }}
                </div>
                {#{{ form_widget(form.cover_change_button, {'attr': {'class': 'ui fluid small blue button border-radius-top-none'} }) }}#}
                {{ form_widget(form.cover_crop_values) }}
                {{ form_widget(form.cover_changed) }}
            </div>
        </div>
        <div class="field eight wide column">
            {{ form_label(form.gender) }}
            <div class="ui selection dropdown">
                {{ form_widget(form.gender) }}
                <i class="dropdown icon"></i>
                <div class="default text">Gender</div>
                <div class="menu">
                    <div class="item" data-value="0">Unknown</div>
                    <div class="item" data-value="1">Male</div>
                    <div class="item" data-value="2">Female</div>
                    <div class="item" data-value="3">Attack Helicopter</div>
                </div>
            </div>
        </div>
        <div class="eight wide field">
            {{ form_label(form.birthday) }}
            <div class="three fields">
                <div class="field">
                    {{ form_widget(form.birthday.month) }}
                </div>
                <div class="field">
                    {{ form_widget(form.birthday.day) }}
                </div>
                <div class="field">
                    {{ form_widget(form.birthday.year) }}
                </div>
            </div>
        </div>
        <div class="eight wide field">
            {{ form_label(form.location) }}
            {{ form_widget(form.location) }}
        </div>
        <div class="eight wide field">
            {{ form_label(form.introduction) }}
            {{ form_widget(form.introduction) }}
        </div>
        <div class="field margin-bottom-none">
            {{ form_widget(form.submit, {'attr': {'class': 'ui medium darkblue button'} }) }}
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}