src/ImageBundle/Entity/Image.php
<?php

namespace ImageBundle\Entity;

use UserBundle\Entity\User;

class Image
{
    /** image has been uploaded, but not finalized */
    public const STATUS_UPLOADED = 'uploaded';
    /** image is active and visible to users */
    public const STATUS_ACTIVE = 'active';
    /** image is hidden from the public */
    public const STATUS_HIDDEN = 'hidden';
    /** image has been deleted */
    public const STATUS_DELETED = 'deleted';
    /** image has just been created */
    public const STATUS_NEW = 'new';

    /** image height is bigger than width */
    public const DISPLAY_VERTICAL = 1;
    /** image width is bigger than height */
    public const DISPLAY_HORIZONTAL = 2;

    public const FILE_EXTENSION_JPG = 'jpg';

    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string|null
     */
    private $source;

    /**
     * @var User
     */
    private $user;

    /**
     * @var string
     */
    private $hash;

    /**
     * @var string
     */
    private $fileName;

    /**
     * @var string
     */
    private $fileExtension;

    /**
     * @var int
     */
    private $fileSize;

    /**
     * @var int
     */
    private $display;

    /**
     * @var int
     */
    private $width;

    /**
     * @var int
     */
    private $height;

    /**
     * @var int
     */
    private $thumbnailWidth;

    /**
     * @var int
     */
    private $thumbnailHeight;

    /**
     * @var \DateTime
     */
    private $dateUpdated;

    /**
     * @var \DateTime
     */
    private $dateCreated;

    public function __construct()
    {
        $this->status = self::STATUS_NEW;
        $this->dateUpdated = new \DateTime();
        $this->dateCreated = new \DateTime();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getPartition(): int
    {
        //TODO: have a global for images per partition
        $imagesPerPartition = 5000;
        return ceil($this->getId() / $imagesPerPartition);
    }

    public function getPath(): string
    {
        return "images/preupload/fixedThumbnails/" . $this->getFileName();
    }

    public function getDynamicThumbPath(): string
    {
        //TODO: actually return the thumbnail
        if (file_exists("images/" . $this->getFileName())) {
            return "images/" . $this->getFileName();
        } else {
            return "images/preupload/dynamicThumbnails/" . $this->getFileName();
        }
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): Image
    {
        $this->status = $status;
        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(?string $source): string
    {
        $this->source = $source;
        return $this;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): Image
    {
        $this->user = $user;
        return $this;
    }

    public function getHash(): string
    {
        return $this->hash;
    }

    public function setHash(string $hash): Image
    {
        $this->hash = $hash;
        return $this;
    }

    public function getFileName(): string
    {
        return $this->fileName;
    }

    public function setFileName(string $fileName): Image
    {
        $this->fileName = $fileName;
        return $this;
    }

    public function getDisplay(): int
    {
        return $this->display;
    }

    public function setDisplay(int $display): Image
    {
        $this->display = $display;
        return $this;
    }

    public function getWidth(): int
    {
        return $this->width;
    }

    public function setWidth(int $width): Image
    {
        $this->width = $width;
        return $this;
    }

    public function getHeight(): int
    {
        return $this->height;
    }

    public function setHeight(int $height): Image
    {
        $this->height = $height;
        return $this;
    }

    public function getThumbnailWidth(): int
    {
        return $this->thumbnailWidth;
    }

    public function setThumbnailWidth(int $thumbWidth): Image
    {
        $this->thumbnailWidth = $thumbWidth;
        return $this;
    }

    public function getThumbnailHeight(): int
    {
        return $this->thumbnailHeight;
    }

    public function setThumbnailHeight(int $thumbHeight): Image
    {
        $this->thumbnailHeight = $thumbHeight;
        return $this;
    }

    public function getFileExtension(): string
    {
        return $this->fileExtension;
    }

    public function setFileExtension(string $fileExtension): Image
    {
        $this->fileExtension = $fileExtension;
        return $this;
    }

    public function getFileSize(): int
    {
        return $this->fileSize;
    }

    public function setFileSize(int $fileSize): Image
    {
        $this->fileSize = $fileSize;
        return $this;
    }

    public function getDateUpdated(): \DateTime
    {
        return $this->dateUpdated;
    }

    public function setDateUpdated(\DateTime $dateUpdated): Image
    {
        $this->dateUpdated = $dateUpdated;
        return $this;
    }

    public function getDateCreated(): \DateTime
    {
        return $this->dateCreated;
    }

    public function setDateCreated(\DateTime $dateCreated): Image
    {
        $this->dateCreated = $dateCreated;
        return $this;
    }
}

src/ImageBundle/Resources/views/Default/finishedImageUploads.html.twig
{% block finished_images %}
    {% for image in finishedImageUploads %}
        <div class="image thumbnail" data-image-id="{{ image.id }}">
            <img src="{{ domain }}/{{ image.path }}"/>
        </div>
    {% endfor %}
{% endblock %}

src/ImageBundle/Resources/views/Default/imageThumbnail.html.twig
{% block imageThumbnail %}
    <img src="{{ image.dynamicThumbPath }}" class="image thumbnail" />
{% endblock %}

src/ImageBundle/Resources/views/Default/index.html.twig
{% extends "AppBundle::base.html.twig" %}

{% block title %} Images {% endblock %}

{% block body %}
    <div class="nav-body-gap"></div>
   {# <div class="ui violet segment">
        <img class="ui medium right floated image"
             src="http://orig07.deviantart.net/fbf6/f/2014/185/6/9/_render__6__anime_girl_by_eysaa_renders-d7p71m3.png"
             style="margin-right: -14px; margin-bottom: -14px;">
        <h1 class="ui violet header">Be inspired. Read a quote.</h1>
        <p>
            It's time to go!
        </p>
        <br class="clearfix">
    </div>#}

    <div class="images wrapper">
        {% for image in images %}
            {% include 'ImageBundle:Default:imageThumbnail.html.twig' %}
        {% endfor %}
    </div>

    <div class="ui raised very padded text segment">
        <h2 class="ui header">Dogs Roles with Humans</h2>
        <p>Hey there! Click here to upload an image <button class="ui primary button">upload</button>!</p>
        <p><a id="image-upload-open" href="{{ path('fr_upload_image') }}" class="ui secondary button">New Upload</a></p>
    </div>

    <div id="image-upload" class="ui large modal" style="height: 500px;"></div>
{% endblock %}

src/ImageBundle/Resources/views/Default/unfinishedImageUploads.html.twig
{% block unfinished_images %}
    {% for image in unfinishedImageUploads %}
        <div class="image thumbnail uploaded" data-image-id="{{ image.id }}">
            <div class="dimmer"></div>
            {#<div class="select">SELECT</div>#}
            <img src="{{ domain }}/{{ image.path }}"/>
        </div>
    {% endfor %}
{% endblock %}

src/ImageBundle/Resources/views/Default/upload.html.twig
{% extends "AppBundle::base.html.twig" %}

{% block additional_javascripts %}
    {% javascripts '@ImageBundle/Resources/public/js/uploader.js' %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block body %}
    <div class="nav-body-gap"></div>
    <div class="ui">
        {% if secondStep is same as(1) %}
            <div id="image_upload_step_one" class="display none">
        {% else %}
            <div id="image_upload_step_one">
        {% endif %}
                <div class="ui small steps">
                    <div class="active step">
                        <i class="upload icon"></i>
                        <div class="content">
                            <div class="title">Upload</div>
                            <div class="description">Choose and upload your images</div>
                        </div>
                    </div>
                    <div class="step">
                        <i class="tag icon"></i>
                        <div class="content">
                            <div class="title">Tag</div>
                            <div class="description">Add tags and some other info</div>
                        </div>
                    </div>
                    <div class="step">
                        <i class="check icon"></i>
                        <div class="content">
                            <div class="title">Finalize</div>
                            <div class="description">Confirm and get your images fully uploaded!</div>
                        </div>
                    </div>
                </div>
            <br/>
                <div id="image-upload-messages"></div>
                <div id="image_upload_preview" class="ui segment padded">
                    <div class="background-text">Drag&Drop</div>
                </div>

                <button id="image-upload-start" class="ui darkblue button">Upload</button>
        </div>
        {% if secondStep is same as(1) %}
            <div id="image_upload_step_two">
        {% else %}
            <div id="image_upload_step_two" class="display none">
        {% endif %}
            <div class="ui small steps">
                <div class="disabled step">
                    <i class="upload icon"></i>
                    <div class="content">
                        <div class="title">Upload</div>
                        <div class="description">Choose and upload your images</div>
                    </div>
                </div>
                <div class="active step">
                    <i class="tag icon"></i>
                    <div class="content">
                        <div class="title">Tag</div>
                        <div class="description">Add tags and some other info</div>
                    </div>
                </div>
                <div class="step">
                    <i class="check icon"></i>
                    <div class="content">
                        <div class="title">Finalize</div>
                        <div class="description">Confirm and get your images fully uploaded!</div>
                    </div>
                </div>
            </div>
            <br/>
            <div class="ui padded segment">
                <h4 class="ui horizontal divider header">
                    <i class="image icon"></i>
                    Uploaded images
                </h4>
                <div id="image_upload_unfinished_images">
                {% if secondStep is same as (1) %}
                    {% include 'ImageBundle:Default:unfinishedImageUploads.html.twig' %}
                {% endif %}
                </div>
            </div>
            <div id="tag_section" class="ui segment">
                <h4 class="ui horizontal divider header">
                    <i class="tag icon"></i>
                    Tag selected
                </h4>
                <div id="tagger_box" class="ui icon input">
                    <input type="text" id="tag_search" placeholder="Search tags...">
                    <i class="circular search link icon"></i>
                </div>
                <div id="tag_section_loader" class="ui inverted dimmer">
                    <div class="ui text loader">Loading</div>
                </div>

                <div id="image_upload_show_tags"></div>
            </div>
            <h4 class="ui horizontal divider header">
                <i class="finish icon"></i>
                Finish
            </h4>
            <button id="image_upload_finish" class="ui darkblue button">Finish</button>
        </div>
    </div>
    <div id="image_upload_step_three" class="display none">
        <div class="ui small steps">
            <div class="disabled step">
                <i class="upload icon"></i>
                <div class="content">
                    <div class="title">Upload</div>
                    <div class="description">Choose and upload your images</div>
                </div>
            </div>
            <div class="disabled step">
                <i class="tag icon"></i>
                <div class="content">
                    <div class="title">Tag</div>
                    <div class="description">Add tags and some other info</div>
                </div>
            </div>
            <div class="active step">
                <i class="check icon"></i>
                <div class="content">
                    <div class="title">Finalize</div>
                    <div class="description">Confirm and get your images fully uploaded!</div>
                </div>
            </div>
        </div>
        <br/>
        <div class="ui padded segment">
            <h4 class="ui horizontal divider header">
                <i class="image icon"></i>
                Finished images
            </h4>
            <div id="image_upload_finished_images"></div>
        </div>
        <a href="{{ path('fr_upload_image') }}" class="ui darkblue button">Upload more</a>
    </div>
    <br class="clearfix"/>
{% endblock %}